### ISSUE TITLE
Content removal on down vote

### ISSUE THREAD

**Issue by ollkostin** [Boar-D-White-Foundation/drone#105]
As a chat member, I want to see good content in topics. 

By down voting a video/image/link, I want bot to delete this message. Message should reach N downvotes from chat members to be deleted.

Feature should have an ability to be enabled for certain topics

**Comment by frosthamster** [comment]
smells like gulag, won't fix

**Comment by leshikus** [comment]
Actually when most people vote they don't think if something is good, they just copy behavior which is acceptable in a group. That's why anything "sufficiently different" is voted down.
