### ISSUE TITLE
Supportive pig gifs when you solved a leetcode task

### ISSUE THREAD

**Issue by k3k6u** [Boar-D-White-Foundation/drone#34]
Bot post a daily task looks like:
https://leetcode.com/problems/%name%/

After reply to inital message with solution link looks like:
https://leetcode.com/problems/%name%/submissions/%id%/

Bot will send supportive gif with charming pig from pack https://t.me/addstickers/HohlyGif

**Comment by frosthamster** [comment]
stickers will be too invasive in topics with high activity, we use message reactions to indicate resolution status
but if you really want this feature you can donate us $10k to buy a premium for bot and [unlock](https://github.com/python-telegram-bot/python-telegram-bot/discussions/3960) custom emoji
