### ISSUE TITLE
Complexity analysis for leetcode ultima

### ISSUE THREAD

**Issue by cauchy2384** [Boar-D-White-Foundation/drone#88]
Proposal: do not accept the solution without time & memory complexity in the message hidden with spoiler.
Format: `O(...), O(...)`

**Comment by frosthamster** [comment]
too invasive, won't do

**Comment by frosthamster** [comment]
Will make it non mandatory, only parsing + rating re evaluation (complexity should matter more than total time)
for a solution with complexity we should use a different emoji like 🚀
